accounts/urls.py
from django.urls import path, reverse_lazy
from django.contrib.auth import views as auth_views

from . import views

app_name = 'accounts'

urlpatterns = [
  path('login', views.login_view, name='login'),
  path('logout', views.logout_view, name='logout'),
  path('signup', views.signup, name='signup'),

  # Password reset
  path('password-reset/', views.CustomPasswordResetView.as_view(), name="password_reset"),
  path('password-reset/done/', auth_views.PasswordResetDoneView.as_view(
                                template_name='accounts/reset_password_done.html'
                            ), name="password_reset_done"),
  path('password-reset-confirm/<uidb64>/<token>/', auth_views.PasswordResetConfirmView.as_view(
                                template_name='accounts/reset_password_confirm.html',
                                success_url=reverse_lazy('accounts:password_reset_complete')
                            ), name="password_reset_confirm"),
  path('password-reset-complete/', auth_views.PasswordResetCompleteView.as_view(
                                template_name="accounts/reset_password_complete.html",
                            ), name='password_reset_complete'),
]

blog/urls.py
from django.urls import path

from django.conf import settings
from django.conf.urls.static import static

from . import views

app_name = 'blog'

urlpatterns = [
    path("", views.index, name="home"),

    # path("blog/posts", views.posts_list, name="posts-list"),
    path("blog/<int:year>/<int:month>/<int:day>/<slug:post_slug>",
                                views.post_detail, name="post-detail"),
    path("new-story", views.write_or_edit_story, name="new_story"),
    path("edit/<int:post_id>", views.write_or_edit_story, name="edit_story"),
    path("edit/<int:post_id>/<str:status>", views.write_or_edit_story, name="edit_public_story"),
    path("delete/<int:post_id>", views.delete_story, name="delete_story"),

    # Search result views 
     path('search/<str:query_on>', views.search_results_view, name='search-results'), 

    # User Profile page
    path("u/<str:username>", views.profile_view, name="user-profile"),
    path("u/<str:username>/lists", views.profile_lists_view, name="user-profile-lists"),

    path("u/<str:username>/about", views.profile_about_view, name="user-profile-about"),
    # Use singlepage using APIview
    path("u/<str:username>/about/create-or-edit", views.create_or_edit_profile, name="create-or-edit-profile"),

    # User Following and Follower List 
    path("u/<str:username>/followings", views.followings_view, name="user-followings"),
    path("u/<str:username>/followers", views.followers_view, name="user-followers"),

    # Library Your lists (reading-list), reading history
    path("me/lists/<str:lists_type>", views.library, name="library"),
    # path("me/lists/reading-history", views.reading_history, name="reading-history"),
    path("me/lists/bookmarks/clear-bookmarks", views.clear_bookmarks, name="clear-bookmarks"),
    # path("me/lists/bookmarks/<int:post_id>/delete", views.delete_bookmark, name="delete-bookmark"),
    path("me/lists/reading-history/clear-all", views.clear_history, name="clear-history"),
    # Stories
    path("me/stories/<str:stories>", views.my_stories, name="stories"),
    # path("me/stories/published", views.published_stories, name="published-stories"),
    # path("me/stories/submitted", views.submitted_stories, name="submitted-stories"),

    # Stroy statistics
    path("me/stats", views.stats, name="stats"),

    # List of Categories
    path('topics/', views.category_list, name="category-list"),
    
    # Posts categorized/tagged
    path('tag/<str:slug>', views.tagged_posts, name='tagged-stories'),

    # API view 
    path('search', views.search_modal_result, name='search'), 
    path('follow/<str:username>', views.follow_or_unfollow, name='follow-user'),
    path('like-post/<int:post_id>', views.like_or_unlike_post, name='like-post'),
    path('publish_comment', views.publish_comment, name="publish-comment"),
    path('delete_comment/<int:comment_id>', views.delete_comment, name="delete-comment"),
    # path('edit_comment/<int:comment_id>', views.edit_comment, name="edit-comment"),
    path('like-comment/<int:comment_id>', views.toggle_like_comment, name="toggle-like-comment"),
    path("reply/<int:comment_id>", views.reply_comment, name="reply-comment"),
    path('follow-topic/<str:tag_slug>', views.toggle_topic_follow, name='follow_topic'),
    path('bookmark-post/<int:post_id>', views.add_or_remove_bookmark, name='bookmark_post'),

]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

finalproject/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('blog.urls')),
    path('accounts/', include('accounts.urls')),
]

urlpatterns += static(
        settings.STATIC_URL, document_root=settings.STATIC_ROOT
    ) + static(
        settings.MEDIA_URL, document_root=settings.MEDIA_ROOT
    )

accounts/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser
from django.contrib.contenttypes.fields import GenericRelation


# Create your models here.
class User(AbstractUser):
    
    followings = models.ManyToManyField('self', through='UserRelation', 
                                        symmetrical=False, related_name="followers")
    
    # roles = models.ManyToManyField('UserRole', default='regular')
    interests = GenericRelation('blog.TaggedItem',
                                object_id_field='object_id',
                                content_type_field='content_type',
                                related_query_name='topic_followers')
   
    # REQUIRED_FIELDS = ['interests']


class UserRole(models.Model):
    ADMIN = 'admin'
    STAFF = 'staff'
    REGULAR = 'regular'
    AUTHOR = 'author'
    EDITOR = 'editor'
    PUBLICTION_OWNER = 'pub_owner'

    role = models.CharField(max_length=10, choices=[(ADMIN, 'Admin'), 
                                                    (STAFF, 'Staff'),
                                                    (REGULAR, 'Regular'),
                                                    (AUTHOR, 'Author'),
                                                    (EDITOR, 'Editor'),
                                                    (PUBLICTION_OWNER, 'pub_owner')
                                                    ])
    
# Intermediary Model
class UserRelation(models.Model):

    user_follower = models.ForeignKey(User, on_delete=models.CASCADE, related_name="follower_users")
    followed_user= models.ForeignKey(User, on_delete=models.CASCADE, related_name="followed_users")

    created_on = models.DateTimeField(auto_now_add=True)
    
    def __str__(self):
        return f"<{self.user_follower.username}> follows {self.followed_user.username}"
    

accounts/views.py
from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.views import PasswordResetView
from django.shortcuts import render, redirect
from django.http import HttpResponse, HttpResponseRedirect
from django.urls import reverse, reverse_lazy
from django.db import IntegrityError

from .models import User
from blog.models import TaggedItem, Category, Tag

# Create your views here.

def login_view(request):
    if not request.user.is_authenticated:

        if request.method == 'POST':

            username = request.POST['username']
            password = request.POST['password']

            user = authenticate(username=username,password=password)

            if user is not None:
                login(request, user=user)
                return HttpResponseRedirect(reverse("blog:home") )

            return render(request, "accounts/login.html", {
                'message': "Wrong username or password, try again please.",
            })
        else:
            return render(request, "accounts/login.html", {})
    else:
        return redirect("blog:home")


def logout_view(request):
    logout(request)
    return render(request, "accounts/logout.html", {})


def signup(request):
    # Make sure user is signed in
    if request.user.is_authenticated:
        return redirect("blog:home")
    
    # Get categories of higher hierarchy
    categories = Category.objects.filter(parent=None)

    template = "accounts/signup.html"


    if request.method == 'POST':
        first_name = request.POST.get('first_name')
        last_name = request.POST.get('last_name')
        username = request.POST.get('username')
        email = request.POST.get('email')
        password = request.POST.get('password')
        password2 = request.POST.get('confirmation')

        MIN_INTERESTS = 3 # Constant for min user's interests
        selected_interests  = Category.objects.filter(slug__in=request.POST.getlist('categories'))
        slug_categories = request.POST.getlist('categories')

        # Make sure passwords match first
        if password != password2:
            return render(request, template, {
                "message": "Passwords do not match!",
                "categories": categories,
            })
        
        # Try to register user
        try:
            user = User.objects.create_user(username=username, email=email, password=password, \
                                            first_name=first_name, last_name=last_name)
            
            # Make sure atleast 3 interests are selected
            if selected_interests.count() < MIN_INTERESTS:
                return render(request, template, {
                    "message": "Must select atleast three interests",
                    "categories": categories,
                })
            
            # Add interests in to tagged item
            for interest in selected_interests:
                user.interests.create(tag=interest)
                user.save()

        except IntegrityError as ie:
            print(ie)
            return render(request, template, {
                'message': "Username already taken! Try another.",
                "categories": categories,
            })
        
        login(request, user)
        return HttpResponseRedirect(reverse("blog:home"))
    else:
        return render(request, template, {
            'categories': categories,
        })


class CustomPasswordResetView(PasswordResetView):
    email_template_name = 'accounts/password_reset_email.html'
    success_url = reverse_lazy('accounts:password_reset_done')
    template_name = 'accounts/reset_password.html'

accounts/templates/accounts/login.html
{% extends 'base.html' %}

{% block title %} &#8211; Sign in{% endblock %}

{% block content %}

<div class="login-box">
    <div class="container ">
        <div class="row text-center">
            <div class="col-10 col-sm-8 col-md-6 col-lg-5 px-4 form-group rounded mx-auto shadow">
                <h2 class="display-4 my-5">Login</h2>
                {% if message %}
                    <p class="error-msg">{{ message }}</p>
                {% endif %}
                <form action="{% url "accounts:login" %}" method="post">
                    <div class="mb-5">
                        <input required autofocus type="text" name="username" id="username" placeholder="Username" value="{{username}}" class="form-control ps-4 rounded-pill no-shadow">
                        </div>
                        <div class="mb-1">
                            <input required type="password" name="password" id="password" placeholder="Password" value="{{password}}" class="form-control ps-4 rounded-pill no-shadow" >
                        </div>
                        <input type="hidden" name="next" value="{{next}}">
                        {% comment %} {{ form.as_p }} {% endcomment %}
                        {% csrf_token %}
                        <div class="text-start mb-3 ps-4">
                            <a href="{% url 'accounts:password_reset' %}" class="login-box-link">Forgot Password?</a>
                        </div>
                        <div class="mb-3">
                            <input type="submit" class="btn w-100 blg-btn-primary rounded-pill" value="Login">
                        </div>
                    </form>
                    <div class="col mb-5">
                        <p>Do not you have an account? <strong><a href="{% url "accounts:signup" %}" class="login-box-link">Sign Up</a>.</strong></p>
                    </div>
                </div>
            </div>
        </div>
    </div>
{% endblock %}

accounts/templates/accounts/logout.html
{% extends "base.html" %}

{% block content %}
    <div class="container">
      <div class="logout-message mt-5">
        <p class="lh-base"> You have successfully logged out! <strong><a class="link" href="{% url 'accounts:login' %}">Login</a>?</strong></p>
      </div>
    </div>
{% endblock %}

accounts/templates/accounts/password_reset_email.html
<body>
    <h1>Password Reset Request</h1>
    <p>Hi,</p>
    <p>Click the link below to reset your password:</p>
    <a href="{{ protocol }}://{{ domain }}{% url 'accounts:password_reset_confirm' uidb64=uid token=token %}">
        Reset Password
    </a>
    <p>If you didn’t request a password reset, you can safely ignore this email.</p>
</body>

accounts/templates/accounts/reset_password.html
{% extends "base.html" %}

{% block title %} &#8211; Password Reset{% endblock %}


{% block content %}
<div class="container mt-5">
  <h3>Password Reset</h3>
  <hr>
  <div class="row mt-4 justify-content-center">
    <div class="col-8 col-md-6 align-self-md-center text-center">
      Looks like you forgot your password, want to <strong>reset</strong> it?
    </div>
    <div class="col-8 col-md-6 py-5 px-3 form-group shadow mt-3">
      Enter your email to <strong>reset password</strong>.
      <form id="reset_psw-form" method="post" >
        <div class="mt-5">
          <input type="email" name="email" id="id_email" class="form-control px-4 rounded-pill no-shadow" required >
        </div>
        {% csrf_token %}
        <div class="d-flex justify-content-center my-4">
          <input class="btn btn-sm blg-btn-primary rounded-pill px-3"type="submit" name="send_email" value="Send Email">
        </div>
      </form>
    </div>
    <div class="col-8 mt-5 d-flex align-items-center">
      <span class="md-font">Go back to</span>
      <a class="btn btn-sm rounded-pill blg-btn-success ms-3" href="{% url "accounts:login" %}">Sign In</a>
      <span>
      </span>
    </div>
  </div>
 </div>
{% endblock %}

accounts/templates/accounts/reset_password_complete.html
{% extends "base.html" %}

{% block title %} &#8211; Password Reset Complete{% endblock %}


{% block content %}
<div class="container mt-5">
  <h3>Password Reset Complete</h3>
  <div class="row mt-4">
    <div class="col-12 col-md-8">
      Your password was successfully set. <a href="{% url 'accounts:login' %}">Login</a>.
    </div>
  </div>
 </div>
{% endblock %}

accounts/templates/accounts/reset_password_confirm.html
{% extends "base.html" %}

{% block title %} &#8211; Password Reset Confirm{% endblock %}


{% block content %}
  <div class="container mt-5">
    <h3>Password Reset Confirm</h3>
    <div class="row mt-4 mx-auto justify-content-center">
      <div class="col-10 col-sm-8 col-md-6 form-group mt-3 shadow">
        <form method="post" class="p-3 mx-auto">

          {{ form.as_p }}
          {% csrf_token %}
          {% if form.errors %}
            {{ form.errors }}
          {% endif %}
          <div class="d-flex justify-content-center my-4">
            <input class="btn btn-sm blg-btn-primary rounded-pill px-3"type="submit" name="reset-password" value="Reset password">
          </div>
        </form>
        
      </div>
    </div>
  </div>
{% endblock %}

accounts/templates/accounts/reset_password_done.html
{% extends "base.html" %}

{% block title %} &#8211; Password Reset{% endblock %}


{% block content %}
<div class="container mt-5">
  <h3>Password Reset</h3>
  <div class="row mt-4">
    <div class="col-12 col-md-8">
      Please check your email and follow instruction to reset your password.
    </div>
  </div>
 </div>
{% endblock %}

accounts/templates/accounts/signup.html
{% extends "base.html" %}

{% block title %} &#8211; Sign Up{% endblock %}

{% block content %}
<div class="login-box">
  <div class="container">
      <div class="row text-center">
          <div class="col-10 col-sm-9 col-md-8 col-lg-5 px-4 rounded mx-auto bg-light form-group shadow">
              <h2 class="display-5 my-4">Sign Up</h2>
              {% if message %}
                  <p class="error-msg text-small">
                    <span><i class="bi bi-exclamation-circle"></i></span> 
                    {{ message }}
                  </p>
              {% endif %}
              <form action="{% url "accounts:signup" %}" method="post">
                <div class="row mb-2">
                  <div class="col-6">
                    <input required autofocus type="text" name="first_name" id="first-name" placeholder="First name" class="form-control ps-4 rounded-pill no-shadow">
                  </div>
                  <div class="col-6">
                    <input required type="text" name="last_name" id="last-name" placeholder="Last name"  class="form-control ps-4 rounded-pill no-shadow">
                  </div>
                </div>
                <div class="mb-2">
                  <input required type="text" name="username" id="username" placeholder="Username" class="form-control ps-4 rounded-pill no-shadow">
                </div>
                <div class="mb-2">
                  <input required type="email" name="email" id="email" placeholder="Email" class="form-control ps-4 rounded-pill no-shadow" >
                </div>                
                <div class="mb-2">
                  <input required type="password" name="password" id="password1" placeholder="Password" class="form-control ps-4 rounded-pill no-shadow" >
                </div>
                <div class="mb-3">
                  <input required type="password" name="confirmation" id="password2" placeholder="Re-password"  class="form-control ps-4 rounded-pill no-shadow" >
                </div>
                <input type="hidden" name="next" value="{{next}}">

                <!-- Select Section -->
                <div class="mb-3 interests--select-box text-start rounded p-1">
                  <label for="interest-select" class="ps-4">
                    <strong>Your Interests?</strong> <small class="text-muted">(Must select atleast three)</small>
                    <span class="btn btn-sm open-select"><i class="bi bi-caret-right-fill"></i></span>
                  </label>
                  <select required class="mx-auto form-select border-0 rounded no-shadow hide" name="categories" size="8" multiple id="interest-select">
                    {% for category in categories %}
                      <option class= "rounded text-center mx-auto py-1 mb-1" value="{{ category.slug }}">{{ category.name }} </option>
                    {% endfor %}
                  </select>
                </div>
                {% csrf_token %}

                <div class="mb-3">
                    <input type="submit" class="btn blg-btn-primary rounded-pill w-100 signup" value="Sign Up">
                </div>
              </form>
              <div class="col mb-4">
                  <p>Do you have an account? <strong><a href="{% url "accounts:login" %}" class="login-box-link">Sign In</a>.</strong></p>
              </div>
          </div>
      </div>
  </div>
</div>
{% endblock %}

{% block script %}
<script>
   // Interests
    const interestsBox = document.querySelector('.interests--select-box');
    const openSelectBtn = document.querySelector('.open-select');
    const select = document.getElementById('interest-select');

    openSelectBtn.addEventListener('click', (e) => {
      select.classList.toggle('hide');

      // Close Select when clicked outside
      document.addEventListener('click', closeSelect);

    });

    
    const MIN_OPTIONS = 3;
    const signup = document.querySelector('form .signup');
    
    signup.disabled = true;

    select.addEventListener('change', () => {
      if (select.selectedOptions.length < MIN_OPTIONS) {
        signup.disabled = true;
      } else {
        signup.disabled = false;
      }
    });

    // Close Select Modal
    const closeSelect = (e) => {
      if (!e.target.closest('.interests--select-box')) {
        select.classList.add('hide');
        document.removeEventListener('click', closeSelect);
      }
    };
    
  </script>
{% endblock %}