accounts/urls.py
from django.urls import path, reverse_lazy
from django.contrib.auth import views as auth_views

from . import views

app_name = 'accounts'

urlpatterns = [
  path('login', views.login_view, name='login'),
  path('logout', views.logout_view, name='logout'),
  path('signup', views.signup, name='signup'),

  # Password reset
  path('password-reset/', views.CustomPasswordResetView.as_view(), name="password_reset"),
  path('password-reset/done/', auth_views.PasswordResetDoneView.as_view(
                                template_name='accounts/reset_password_done.html'
                            ), name="password_reset_done"),
  path('password-reset-confirm/<uidb64>/<token>/', auth_views.PasswordResetConfirmView.as_view(
                                template_name='accounts/reset_password_confirm.html',
                                success_url=reverse_lazy('accounts:password_reset_complete')
                            ), name="password_reset_confirm"),
  path('password-reset-complete/', auth_views.PasswordResetCompleteView.as_view(
                                template_name="accounts/reset_password_complete.html",
                            ), name='password_reset_complete'),
]

blog/urls.py
from django.urls import path

from django.conf import settings
from django.conf.urls.static import static

from . import views

app_name = 'blog'

urlpatterns = [
    path("", views.index, name="home"),

    # path("blog/posts", views.posts_list, name="posts-list"),
    path("blog/<int:year>/<int:month>/<int:day>/<slug:post_slug>",
                                views.post_detail, name="post-detail"),
    path("new-story", views.write_or_edit_story, name="new_story"),
    path("edit/<int:post_id>", views.write_or_edit_story, name="edit_story"),
    path("edit/<int:post_id>/<str:status>", views.write_or_edit_story, name="edit_public_story"),
    path("delete/<int:post_id>", views.delete_story, name="delete_story"),

    # Search result views 
     path('search/<str:query_on>', views.search_results_view, name='search-results'), 

    # User Profile page
    path("u/<str:username>", views.profile_view, name="user-profile"),
    path("u/<str:username>/lists", views.profile_lists_view, name="user-profile-lists"),

    path("u/<str:username>/about", views.profile_about_view, name="user-profile-about"),
    # Use singlepage using APIview
    path("u/<str:username>/about/create-or-edit", views.create_or_edit_profile, name="create-or-edit-profile"),

    # User Following and Follower List 
    path("u/<str:username>/followings", views.followings_view, name="user-followings"),
    path("u/<str:username>/followers", views.followers_view, name="user-followers"),

    # Library Your lists (reading-list), reading history
    path("me/lists/<str:lists_type>", views.library, name="library"),
    # path("me/lists/reading-history", views.reading_history, name="reading-history"),
    path("me/lists/bookmarks/clear-bookmarks", views.clear_bookmarks, name="clear-bookmarks"),
    # path("me/lists/bookmarks/<int:post_id>/delete", views.delete_bookmark, name="delete-bookmark"),
    path("me/lists/reading-history/clear-all", views.clear_history, name="clear-history"),
    # Stories
    path("me/stories/<str:stories>", views.my_stories, name="stories"),
    # path("me/stories/published", views.published_stories, name="published-stories"),
    # path("me/stories/submitted", views.submitted_stories, name="submitted-stories"),

    # Stroy statistics
    path("me/stats", views.stats, name="stats"),

    # List of Categories
    path('topics/', views.category_list, name="category-list"),
    
    # Posts categorized/tagged
    path('tag/<str:slug>', views.tagged_posts, name='tagged-stories'),

    # API view 
    path('search', views.search_modal_result, name='search'), 
    path('follow/<str:username>', views.follow_or_unfollow, name='follow-user'),
    path('like-post/<int:post_id>', views.like_or_unlike_post, name='like-post'),
    path('publish_comment', views.publish_comment, name="publish-comment"),
    path('delete_comment/<int:comment_id>', views.delete_comment, name="delete-comment"),
    # path('edit_comment/<int:comment_id>', views.edit_comment, name="edit-comment"),
    path('like-comment/<int:comment_id>', views.toggle_like_comment, name="toggle-like-comment"),
    path("reply/<int:comment_id>", views.reply_comment, name="reply-comment"),
    path('follow-topic/<str:tag_slug>', views.toggle_topic_follow, name='follow_topic'),
    path('bookmark-post/<int:post_id>', views.add_or_remove_bookmark, name='bookmark_post'),

]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

finalproject/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('blog.urls')),
    path('accounts/', include('accounts.urls')),
]

urlpatterns += static(
        settings.STATIC_URL, document_root=settings.STATIC_ROOT
    ) + static(
        settings.MEDIA_URL, document_root=settings.MEDIA_ROOT
    )

blog/forms.py
from django import forms
from django.contrib.contenttypes.forms import generic_inlineformset_factory  

from ckeditor.widgets import CKEditorWidget       
from .models import BlogPost, UserProfile, Category, TaggedItem, Tag, Comment


# Create custom form
class BlogPostForm(forms.ModelForm):
    content = forms.CharField(widget=CKEditorWidget())
    
    # Remove all fields label
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)

        for key, field in self.fields.items():
            # if field.label != "Featured image":
            field.label = ""
    
        
    class Meta:
        model = BlogPost
        
        fields = ("title", "subtitle", "content") # /*"featured_image", "featured_image_caption",
        widgets = {
            "title": forms.TextInput(attrs={"class": "form-control no-shadow fs-3", "placeholder": "Title"}),
            "subtitle": forms.TextInput(attrs={"class": "form-control no-shadow", "placeholder": "Subtitle"}),
            # "featured_image": forms.TextInput(attrs={"class": "form-control no-shadow", "type": "file", "placeholder": "choose"}),
            # "featured_image_caption": forms.TextInput(attrs={"class": "form-control no-shadow", "placeholder": "Featured img caption"}),
            "content": forms.Textarea(attrs={'class': 'form-control', })
            
        }


class CommentForm(forms.ModelForm):
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        
        for key, field in self.fields.items():
            field.label = ""
        

    class Meta:
        model = Comment

        fields = ("body",)
        widgets = {
            "body": forms.Textarea(attrs={'class': 'form-control rounded no-shadow txta-mod', "rows": 1, })
        }

blog/views.py
import json
import datetime

from django.utils import timezone
from django.shortcuts import render, get_object_or_404, redirect
from django.http import HttpResponse, HttpResponseRedirect, JsonResponse, Http404
from django.urls import reverse
from django.contrib.auth.decorators import login_required
from django.views.decorators.http import require_POST
from django.views.decorators.cache import cache_page

from django.db.models import Count

from accounts.models import User
from .models import (BlogPost, UserProfile, Category, 
                     Comment, Tag, TaggedItem, BlogBookmark, 
                     BlogHistory)
from .forms import BlogPostForm, CommentForm

from .custom_decorators.decorators import owner_required

# Create your views here.

def index(request):
    ''' 1. For annonymous user:
          View Trending Posts: use the most recent posts with in this week,
          then use number of likes ,
          then number of read history, then number of 
        2. For signed in  user:
         2.1 'For You' page: view posts from author 
                - previously liked, read, bookmarked & followed by current user
                - and in addition posts with tags the current user interested in
                - and this week trending post
         2.2 '?feed=following' page: view posts from author the current user follows
         2.3 'tag=<tag slug>' page: view posts with a <tag> the current user interested in
    '''
    # Current User
    user = request.user

    now = timezone.now()
    weektime = now - datetime.timedelta(days=7) # With in a week(7 days)

    if not user.is_authenticated:

        #  Get this week's trending posts limted to 5 posts
        trending_posts = BlogPost.all_published.annotate(
                                    tot_likes=Count('like_users'), 
                                    tot_read=Count('reading_history')
                                    ).filter(
                                        published_on__gte=weektime,
                                    ).order_by('-tot_likes', '-tot_read')[:5] 
            
        # Get most read posts 
        most_read_posts = BlogPost.all_published.select_related(
                                        'author', 'author__profile'
                                    ).prefetch_related(
                                        'bookmarks', 'tags', 
                                        'tags__topic_followers'
                                    ).annotate(
                                        tot_read=Count('reading_history'),
                                        tot_tags_followers=Count('tags__topic_followers')
                                    ).order_by('-tot_read', '-tot_tags_followers')
        
        # Get tags from most read posts
        tags = Tag.objects.filter(
                                id__in=most_read_posts[:6].values_list('tags__tag', flat=True)
                            )

        return render(request, "blog/index.html", {
            "trendings": trending_posts,
            "posts": most_read_posts,
            'tags': tags
        })

    # Dashboard view when user is signed in,
    else:
        # Topics the user is interested in        
        interests = TaggedItem.objects.select_related(
                                    'tag'
                                    ).prefetch_related(
                                        'similar_posts'
                                    ).filter(topic_followers=user)
        
        three_days_before = now - datetime.timedelta(days=3)

        # Latest Trending posts with in atleast three days
        latest_trending_posts = BlogPost.all_published.select_related(
                                            'author', 'author__profile',
                                        ).prefetch_related(
                                            'tags', 'tags__tag', 'like_users', 'reading_history'
                                        ).annotate(
                                            tot_likes=Count('like_users', distinct=True),
                                            tot_read=Count('reading_history', distinct=True)
                                        ).filter(
                                            published_on__gte=three_days_before,
                                        )
        
        # Get Latest trending posts' tags/topics  
        recommended_topics= Tag.objects.filter(
                                id__in=latest_trending_posts.order_by().values_list('tags__tag')
                            )[:9]

        recent_bookmarks = BlogBookmark.objects.select_related(
                                                'bookmark_post',
                                            ).filter(
                                                bookmark_by=user,
                                                created_on__gte=three_days_before
                                            )
        
        # Initial context
        context = {
            'interests' : interests,
            'latest_trending_posts': latest_trending_posts[:5], # only five posts
            'recommended_topics': recommended_topics,
            'recent_bookmarks': recent_bookmarks,
        }


        feed = request.GET.get('feed')
        tag =  request.GET.get('tag')
 
        if feed == "following":
            # template_name = "blog/dashboard.html"
            posts = BlogPost.all_published.select_related(
                                        'author', 'author__profile'
                                    ).prefetch_related(
                                        'author__followings',
                                        'like_users'
                                    ).filter(author__in=user.followings.all())

            context.update({'posts': posts, 'section': 'following'})

        # POSTS UNDER CURRENT USER INTERESTS in Dashboard page
        elif tag:
            # Query for posts filter from tag slug
            posts = BlogPost.all_published.select_related(
                                                'author', 'author__profile'
                                            ).prefetch_related(
                                                'tags', 'like_users', 'bookmarks'
                                            ).filter(
                                                tags__tag__slug=tag
                                            )
            # Update context
            context.update({'posts': posts, 'section': tag})
        else:
            # Simple database query to list blog posts for the particular user
            
            # Other posts from users previously liked by current user
            # Get author of liked user
            liked_authors =  user.liked_posts.order_by().values_list('author', flat=True) #user.liked_posts.values_list()
           
            # Posts from users followed by current user
            followed_authors = user.followings.values_list('id', flat=True)
            
            
            # Posts from user once viewed/reacted on by this current user
            read_authors = user.read_history_posts.order_by().values_list('author', flat=True)
            
            # Posts from user previously bookmarked by this current user
            bookmarked_authors = user.bookmarked_posts.order_by().values_list('author', flat=True)
           
            # Combined authors 
            authors = liked_authors.union(followed_authors, read_authors, bookmarked_authors)

            # TODO: posts recommended by the admin
            # This week trending posts 
            trending_posts = BlogPost.all_published.select_related(
                                        'author', 'author__profile'
                                    ).prefetch_related(
                                        'tags', 'bookmarks', 'like_users', 'reading_history'
                                    ).annotate(
                                        tot_likes=Count('like_users'), 
                                        tot_read=Count('reading_history')
                                    ).filter(
                                        published_on__gte=weektime,
                                    ).order_by('-tot_likes', '-tot_read') 
            
            # posts from users the current user interested in topics
            interest_posts = BlogPost.all_published.select_related(
                                                        'author', 'author__profile'
                                                    ).prefetch_related(
                                                        'tags', 'bookmarks', 'like_users', 'reading_history'
                                                    ).filter(
                                                        tags__tag__in=interests.values_list('tag')
                                                    )
            
            
            posts = BlogPost.all_published.select_related(  
                                                'author', 'author__profile'
                                            ).prefetch_related(
                                                'tags', 'bookmarks', 'like_users', 'reading_history'
                                            ).filter(
                                                # Union authors of followed authors,
                                                # authors of previously liked posts,
                                                # authors of previously read posts
                                                # and authors of previously bookmarked posts
                                                author__in=authors,
                                            ).annotate(
                                                tot_likes=Count('like_users'),
                                                tot_bookmarks=Count('bookmarks'),

blog/templates/blog/comment__reply.html
{% load static %}

{% load custom_tags_filter %}

{% with commentby=comment.author parent=comment.parent comment_id=comment.id like_users=comment.like_users.all like_counts=comment.like_users.count %}
<div class="container mt-2" id="comment-row-{{ comment_id }}">
  <div class="row md-font">
    <div class="col-12 col-md-8 mx-auto">
      <div class="d-flex gap-2 fw-600">
        <div class="align-self-center">
          <!-- TODO  __Implement the commenter avatar -->
          {% if not commentby.profile.avatar %}
            <span><i class="bi bi-person-circle" style="font-size: 1.5rem; color: gray;"></i></span>
          {% else %}
            <img class="user-profile-img" src="{% static commentby.profile.avatar.url %}" alt="User profile picture">
          {% endif %}
        </div>
        <div class="">
          <span class="text-capitalize">
            <!-- All links to user profile must have className username -->
            <a href="{% url 'blog:user-profile' user %}" class="link username">{{ commentby.first_name }} {{ commentby.last_name }}</a> 
            <span> &#8226; </span> 
            {% if user == commentby %}
              <span class="delete-comment-parent" id="parent-{{ comment_id }}">
                <span id="comment-del-btn-{{comment_id}}" class="link delete-comment-btn">Delete</span>
                <!-- TODO: Delete Comment Modal -->
                <div class="rounded shadow hide border p-2 delete-comment-modal-box" id="delete-comment-modal-{{comment_id}}" >
                  <div class="p-2 bg-white text-center">
                    <span class=""><i class="bi bi-info-circle-fill"></i> <span>Are you sure you want to delete this comment?</span></span>
                  </div>
                  <div class="d-flex justify-content-between">
                    <div class="btn close-btn">
                      Cancel
                    </div>
                    <div class="">
                      <form action="{% url "blog:delete-comment" comment_id %}" method="post">
                        {% csrf_token %}
                        {% comment %} <input type="hidden" name="comment" value="{{comment_id}}"/> {% endcomment %}
                        <input class="btn" type="submit" value="Yes"/>
                      </form>
                    </div>
                  </div>
                </div>
              </span>
              <!-- TODO - IMPLEMENT EDIT FUNCTIONALITY -->
              <!--
              <span> &#8226; </span> 
              <span>
                <span class="text-muted" >Edit</span>
              </span> -->

            {% else %}
              <span class="link-success follow-actio " id="" data-username="{{commentby}}">
                {% if user in commentby.followers.all %}Unfollow{%else%}Follow{% endif %}
              </span>
            {% endif %}
          </span>
          <div class="">
            <!--div class="md-font">
              {% comment %} <span class="text-muted">Published in</span> Pulication Name {% endcomment %}
            </div>-->
            <span class="text-muted">
              {{ comment.created_on | timesince }} 
              <!--{% if post.published_on != post.updated_on %} 
                (Updated {{ post.updated_on | timesince }} ago)
              {% endif %}-->
            </span>
          </div>
        </div>
      </div>
    </div>

    <!-- Comment body -->
    <div class="col-12 col-md-8 mx-auto pb-3 mt-2">
      {{ comment.body | safe }}
    </div>
    <!-- Comment like & reply -->
    <div class="col-12 col-md-8 mx-auto">
      <div class="d-flex d-md-flex-none justify-content-between border-bottom pb-2">
        <div class="link comment-like" id="comment-like-{{comment_id}}" data-action="{% if user in like_users %}un{% endif %}like">
          <span><i class="bi bi-hand-thumbs-up{% if user in like_users %}-fill{% endif %}"></i></span>
          <span class="comment_total-likes">{{ like_counts |shortnum}}</span>
        </div>
        <div id="comment-reply-{{comment_id}}" class="link comment-reply" title="Reply">
          <span><i class="bi bi-chat"></i></span> <span class="reply-count">{{comment.replies.count}}</span>
        </div>
      </div>
    </div>
    <div id= "comment-replies-{{comment_id}}-list" class="col-12 mx-auto replies-list hide">    
      <div class="col col-md-8 mx-auto" id="reply-form-{{comment_id}}">
        <!-- view comment reply form -->
      </div>      
      <!-- Replies view -->
      {% for reply in comment.replies.all %}
        {% include "blog/comment__reply.html" with comment=reply %}
      {% endfor %}
    </div>
  </div>
</div>
{% endwith %}

blog/templates/blog/profile.html
{% extends 'base.html' %}

{% load static %}

{% block title %}
{% block profile_title %} {% endblock %} &#8211; {{ username }}
{% endblock %}

{% block content %}
  {% with req_username=user.username followers=profile_user.followers followings=profile_user.followings.all  %}
  <div class="container">
    <div class="row">
      <div class="col-12 col-lg-8">
        <div class="profile-header pt-5">
          <div class="row">
            <div class="col-12">
              <div class="row align-items-center mb-3">
                <div class="col-2 col-md-1 d-lg-none mx-auto  profile-photo">
                  {% if not profile.avatar %}
                    <div class="rounded-circle username-first" >
                      {{ username|first }}
                    </div>
                  {% else %}
                    <div class="">
                      {% comment %} <img  class="img-fluid rounded-circle menu-user-profile" src="{% static "images/avatar/imgbin-avatar-drawing-redhead-avatar-woman-.jpg" %}" alt="User profile picture"> {% endcomment %}
                      <img class="img-fluid user-pic rounded-circle" src="{% static profile.avatar.url %}" alt="User profile picture">
                    </div>
                  {% endif %}
                </div>
                <div class="col-10 col-md-8 ps-0 ps-lg-4 me-md-auto">
                  <h3 class="user-fullname mb-0 text-capitalize">{{ profile_user.first_name}} {{ profile_user.last_name}}</h3>
                  <div class="d-md-none lh-sm fw-400 ">
                    <a href="{% url "blog:user-followers" username %}" class="link-none">
                      <span class="follower-count">{{ followers.count }}</span> Follower{{ followers.count | pluralize}}</a>
                  </div>
                </div>
                {% if req_username != username %}
                <div class="col-12 col-md-3 my-3 d-lg-none d-flex align-items-center justify-content-between justify-content-md-end gap-2 follow-subscribe-box">
                  <button id="follow-action" class="btn blg-btn-success rounded-pill follow-action" data-username="{{username}}">
                    {% if user in followers.all %}Unfollow{%else%}Follow{% endif %}
                  </button>
                  {% comment %} <div >
                  </div> {% endcomment %}
                  <div>
                    <button class="btn blg-btn-success">Subscribe</button>
                  </div>
                </div>
                {% endif %}
              </div>
            </div>
            <div class="col-12 d-flex align-items-end fw-500 mb-4 gap-2 sub-header">
              <div class="px-3 py-2 profile_home ">
                <a class="link-reg" href="{% url "blog:user-profile" username %}">Home</a>
              </div>
              <!-- Only if user has bookmark/reading lists  -->               
              {% if req_username == username and has_bookmark %}
              <div class="px-3 py-2 profile_lists">
                <a class="link-reg" href="{% url "blog:user-profile-lists" username %}">Lists</a>
              </div>
              {% endif %}
              <div class="px-3 py-2 profile_user_about">
                <a class="link-reg" href="{% url "blog:user-profile-about" username %}">About</a>
              </div>
            </div>
            <div class="col-12">
              {% block profile_content %}
              {% endblock %}
            </div>
            <!-- Home view List of user's own public posts -->
            <div class="col-12 profile--home-view">
                <!-- TODO: if posts exist show published posts otherwise notify user  -->
                {% include "blog/post_list.html" %}
            </div>
          </div>
        </div>  
      </div>

      <!-- About User Side Bar -->
      <aside class="col-lg-4 py-5 aside lg-aside-sticky half-pos border-start">
        <div class="container md-font">
          <div class="row">
            <div class="col-12 aside--profile-photo">
              {% if not profile.avatar %}
                <div class="rounded-circle username-first xxl-font" >
                  {{ username|first }}
                </div>
              {% else %}
                <div class="">
                  <img class="img-fluid user-pic rounded-circle" src="{% static profile.avatar.url %}" alt="User profile picture">
                </div>
              {% endif %}
            </div>
            <div class="col-12 mb-3">
              <h3 class="text-capitalize lg-font">{{ profile_user.first_name}} {{ profile_user.last_name}}</h3>
              <div class="lh-sm fw-400 ">
                <a href="{% url "blog:user-followers" username %}" class="link-none">
                  <span class="follower-count">{{ followers.count }}</span> Follower{{followers.count | pluralize }}
                </a>
              </div>
            </div>
            <div class="col user-profile--membership-info mb-2">
              <!--TODO  Check if user is a member or a friend or neither-->
              {% if not True %}
              <span><i class="bi bi-person-check"></i></span> Member of All-in (only if member)
              {% elif not True %}
              <span><i class="bi bi-patch-check-fill"></i></span> Friend of All-in (only if friend)
              {% endif %}
            </div>
            <div class="col-12 user-profile-bio mb-2">
              {% if profile.date_of_birth %} 
                <p>Date of Birth: {{ profile.date_of_birth }}</p> 
              {% endif %}
              {% if profile.bio  %}<p>Bio: {{ profile.bio }}</p> {% endif %}
            </div>

            <!-- Follow and Subscribe buttons -->
            {% if req_username != username %}
            <div class="col-12 d-flex align-items-center gap-2 mb-3">
              <button id="follow-action" class="btn btn-sm blg-btn-success py-2 px-3 rounded-pill follow-action"
               data-username="{{username}}">
                {% if user in followers.all %}Unfollow{% else %}Follow{% endif %}
              </button>
              {% comment %} <div >
              </div> {% endcomment %}
              <div>
                <button class="btn btn-sm blg-btn-success py-2">Subscribe</button>
              </div>
            </div>
            {% endif %}
            <div class="col-12 user-profile-following-lists my-4">
              <h5 class="n-font">Following</h5>
              <p>List of Users Following this users</p>
              {% for following in followings|slice:'6' %}
                <a href="{% url 'blog:user-profile' following.username %}" class="link-none">{{ following|capfirst }}</p>
              {% endfor %}
              <a href="{% url "blog:user-followings" username %}" class="btn btn-sm blg-btn-secondary">Sea all</a>
            </div>

            <!--<div class="col-12 user-profile-lists mb-3">
              <h5 class="n-font">Lists</h5>
              All lists here
              <button class="btn btn-sm blg-btn-secondary">Sea all</button>
            </div>-->
          </div>
        </div>
      </aside>

    </div>  
  </div>
  {% endwith %}
{% endblock %}

{% block script %}
  <!-- Access util.js file/module to get functions -->
  <script src="{% static "js/util.js" %}" ></script>
  <script>
    // Work with toggling of Follow functionality
    const followBtns = document.querySelectorAll('.follow-action');
    const followerCounts = document.querySelectorAll('.follower-count');

    followBtns.forEach(followBtn => {
      followBtn.addEventListener('click', () => { 
        // Fetch api and toggle follow
        toggleFollow(followBtns, followerCounts);
      });

    });

    // BOOKMARK and UNBOOKMARK posts 
    const bookmarkBtns = document.querySelectorAll('.bookmark');
    if (bookmarkBtns !== null) {
      bookmarkBtns.forEach(bookmarkBtn => {
        bookmarkBtn.addEventListener('click', (e) => {   

          let post_id = bookmarkBtn.id.match(/\d+/)[0];

          // Fetch data and toggle top and bottom bookmark icon     
          fetchNToggle({
            btns: bookmarkBtn, 
            url:`/bookmark-post/${post_id}`,
            method: 'POST',
            iconName: 'bookmark',
          }); // Bookmark on single post
    
        });
      });
    }
    
  </script>
{% endblock  %} 

blog/templates/blog/user_row.html
{% load static %}

<div class="col-12 col-lg-8">
  <div class="row mt-2">
    <!-- User Image View (checked with membership (member or friend) mark)-->
    <div class="col-1 p-0 prof-pic-section">
      <a href="{% url "blog:user-profile" a_user.username %}" class="navlink-hvr">
        {% if not a_user.profile.avatar  %}
        <div class="prof-pic-anonymous">
          <i class="bi bi-person-fill"></i>
        </div>
        {% else %}
        <img class="user-profile-img" src="{% static a_user.profile.avatar.url %}" alt="User profile picture">
        {% endif %}
      </a>	
    <!--<img class="img-fluid rounded-circle" width="16" height="16" src="{% static "images/default.png" %}" alt="Profile-pic"> -->
    </div>

    <div class="col-8">
      <div class="d-flex">
        <!-- Username or firstname Lastname -->
        <div class="username">{{ a_user.first_name }} {{ a_user.last_name }}</div>
        
        <!-- Bio If there is -->
        {% if a_user.profile.bio %}
        <span>  &#8226; </span>
        <div class="bio">
          {{ a_user.profile.bio | truncatewords:10 }}
        </div>
        {% endif %}
      </div>

    </div>
    <div class="col-3">
      <!-- Follow/unfollow Button (based on the viewing user follow or unfollow )-->
      {% if user.username != a_user.username %}
        <button id="follow-action-{{a_user.username}}" 
          class="btn btn-sm blg-btn-success px-3 rounded-pill follow-action"
          data-username="{{ a_user.username}}">
            {% if a_user in user.followings.all %}Unfollow{% else %}Follow{% endif %}
        </button>
      {% endif %}
    </div>      
  </div>
</div>